package gov.iti.jets.persistence.entities;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;

import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

import jakarta.xml.bind.annotation.XmlRootElement;


import java.util.ArrayList;

import java.util.List;


/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "ecommerce_schema")
@XmlRootElement
public class Category implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "category_id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "value", nullable = false, length = 45)
    private String value;

    @Column(name = "description", length = 150)
    private String description;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "product_has_category", catalog = "ecommerce_schema", joinColumns = {
            @JoinColumn(name = "category_id", nullable = false, updatable = false) }, inverseJoinColumns = {
                    @JoinColumn(name = "product_id", nullable = false, updatable = false) })
    private List<Product> products = new ArrayList<Product>();

    public Category() {
    }

    public Category(String value) {
        this.value = value;
    }

    public Category(String value, String description, List<Product> products) {
        this.value = value;
        this.description = description;
        this.products = products;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


   
    public List<Product> getProducts() {
        return this.products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    @Override
    public String toString() {
        return "Category [description=" + description + ", id=" + id + ", value=" + value + "]";
    }

}
